spring.application.name=backend
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# Firebase Config (loaded from environment variables)
firebase.apiKey=${FIREBASE_API_KEY}
firebase.authDomain=${FIREBASE_AUTH_DOMAIN}
firebase.projectId=${FIREBASE_PROJECT_ID}
firebase.storageBucket=${FIREBASE_STORAGE_BUCKET}
firebase.messagingSenderId=${FIREBASE_MESSAGING_SENDER_ID}
firebase.appId=${FIREBASE_APP_ID}
firebase.measurementId=${FIREBASE_MEASUREMENT_ID}

# Google Gemini API
gemini.api.key=${GEMINI_API_KEY}
